# Настройки плагина
minPlayTimeHours: 10  # Минимальное количество часов, после которого слежка отключается
banCommand: "ban {player} Подозрительное поведение"  # Команда для бана
teleportCommand: "/tp {player} {x} {y} {z}" # Команда для телепортации
some-setting: 10